defmodule AdventOfCode.Solution.Year2025.Day07Test do
  use ExUnit.Case, async: true

  import AdventOfCode.Solution.Year2025.Day07

  setup do
    [
      input: """
      .......S.......
      ...............
      .......^.......
      ...............
      ......^.^......
      ...............
      .....^.^.^.....
      ...............
      ....^.^...^....
      ...............
      ...^.^...^.^...
      ...............
      ..^...^.....^..
      ...............
      .^.^.^.^.^...^.
      ...............
      """
    ]
  end

  test "part1", %{input: input} do
    result = part1(input)

    assert result == 21
  end

  test "part2", %{input: input} do
    result = part2(input)

    assert result == 40
  end
end
